server_domain = 'http://localhost:8000'
chat_completion_url = f'{server_domain}/api/v1/chat/completion'
file_list_url = f'{server_domain}/api/v1/file/list'
login_url = f'{server_domain}/api/v1/user/login'
register_url = f'{server_domain}/api/v1/user/register'
file_text_extract_url = f'{server_domain}/api/v1/file/text/extract'
chat_text_extract_url = f'{server_domain}/api/v1/chat/text/extract'
chat_file_summary_url = f'{server_domain}/api/v1/chat/summary'
